# Generated by Django 2.1.1 on 2018-09-18 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Authors',
            new_name='Author',
        ),
        migrations.AddField(
            model_name='book',
            name='written_by',
            field=models.ManyToManyField(related_name='books_written', to='books_authors.Author'),
        ),
    ]
