# Generated by Django 2.1.1 on 2018-09-20 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amadon_app', '0002_auto_20180919_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
